### ISSUE TITLE
Line control handles scrolling issue

### ISSUE THREAD

**Issue by shujaatak** [benthillerkus/smooth_shadow#1]
In Google Chrome I scrolled [Smooth Shadow](https://benthillerkus.github.io/smooth_shadow/) page but I noticed that the line control handles do not scroll with the rest of the UI.

![image](https://github.com/benthillerkus/smooth_shadow/assets/14161646/8044b0da-9a64-4b86-8cad-3e8ae6216e96)

**Comment by benthillerkus** [comment]
yup, noticed that too
